spring.application.name=MyJournal
spring.mongodb.uri=mongodb+srv://gollagrishma807_db_user:Test12345@cluster0.l9kpsii.mongodb.net/journal?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true